fuzz(ci): add coregraphics/wic harnesses and native matrices

diff --git a/fuzz/Makefile.am b/fuzz/Makefile.am
--- a/fuzz/Makefile.am
+++ b/fuzz/Makefile.am
@@ -46,10 +46,19 @@ noinst_PROGRAMS = \
     fuzz-loader-builtin-struct-hdr-header-libfuzzer \
     fuzz-loader-builtin-struct-pic-structure-libfuzzer \
     fuzz-loader-builtin-struct-bmp-dib-libfuzzer
+if HAVE_COREGRAPHICS
+noinst_PROGRAMS += \
+    fuzz-loader-coregraphics-libfuzzer
+endif
+if HAVE_WIC
+noinst_PROGRAMS += \
+    fuzz-loader-wic-libfuzzer
+endif
 endif
 
 EXTRA_DIST = \
     fuzz-loader-builtin-libfuzzer.c \
+    fuzz-loader-component-libfuzzer.c \
     fuzz-loader-builtin-struct-common.h \
     fuzz-loader-builtin-struct-runtime.c \
     fuzz-loader-builtin-struct-png-chunk-libfuzzer.c \
@@ -172,13 +181,40 @@ fuzz_loader_builtin_struct_bmp_dib_libfuzzer_CFLAGS = $(FUZZ_COMMON_CFLAGS)
 fuzz_loader_builtin_struct_bmp_dib_libfuzzer_LDFLAGS = $(FUZZ_COMMON_LINK_FLAGS)
 fuzz_loader_builtin_struct_bmp_dib_libfuzzer_LDADD = $(FUZZ_COMMON_LINK_LIBS)
 
+if HAVE_COREGRAPHICS
+fuzz_loader_coregraphics_libfuzzer_SOURCES = \
+    $(srcdir)/fuzz-loader-component-libfuzzer.c \
+    $(srcdir)/fuzz-loader-builtin-struct-runtime.c
+fuzz_loader_coregraphics_libfuzzer_CPPFLAGS = \
+    $(FUZZ_COMMON_CPPFLAGS) \
+    -DFUZZ_LOADER_COMPONENT_NAME=\"coregraphics\"
+fuzz_loader_coregraphics_libfuzzer_CFLAGS = $(FUZZ_COMMON_CFLAGS)
+fuzz_loader_coregraphics_libfuzzer_LDFLAGS = $(FUZZ_COMMON_LINK_FLAGS)
+fuzz_loader_coregraphics_libfuzzer_LDADD = $(FUZZ_COMMON_LINK_LIBS)
+endif
+
+if HAVE_WIC
+fuzz_loader_wic_libfuzzer_SOURCES = \
+    $(srcdir)/fuzz-loader-component-libfuzzer.c \
+    $(srcdir)/fuzz-loader-builtin-struct-runtime.c
+fuzz_loader_wic_libfuzzer_CPPFLAGS = \
+    $(FUZZ_COMMON_CPPFLAGS) \
+    -DFUZZ_LOADER_COMPONENT_NAME=\"wic\"
+fuzz_loader_wic_libfuzzer_CFLAGS = $(FUZZ_COMMON_CFLAGS)
+fuzz_loader_wic_libfuzzer_LDFLAGS = $(FUZZ_COMMON_LINK_FLAGS)
+fuzz_loader_wic_libfuzzer_LDADD = $(FUZZ_COMMON_LINK_LIBS)
+endif
+
 FUZZ_BUILTIN_CORPUS ?= $(top_srcdir)/images
 FUZZ_BUILTIN_ARGS ?=
 FUZZ_BUILTIN_FORMATS = png gif jpeg pnm sixel hdr psd pic bmp
 FUZZ_STRUCT_CORPUS ?= $(FUZZ_BUILTIN_CORPUS)/struct
 FUZZ_STRUCT_ARGS ?= $(FUZZ_BUILTIN_ARGS)
+FUZZ_COMPONENT_CORPUS ?= $(FUZZ_BUILTIN_CORPUS)/component
+FUZZ_COMPONENT_ARGS ?= $(FUZZ_BUILTIN_ARGS)
 
 .PHONY: run-loader-builtin run-loader-builtin-formats \
+    run-loader-coregraphics run-loader-wic \
     run-struct-push-set run-struct-full-set
 
 run-loader-builtin: fuzz-loader-builtin-libfuzzer$(EXEEXT)
@@ -206,6 +242,34 @@ run-loader-builtin-formats: fuzz-loader-builtin-libfuzzer$(EXEEXT)
 			FUZZ_BUILTIN_CORPUS='$(FUZZ_BUILTIN_CORPUS)' \
 			FUZZ_BUILTIN_ARGS='$(FUZZ_BUILTIN_ARGS)' || exit $$?; \
 	done
+
+if HAVE_COREGRAPHICS
+run-loader-coregraphics: fuzz-loader-coregraphics-libfuzzer$(EXEEXT)
+	@set -eu; \
+	target="$(abs_builddir)/fuzz-loader-coregraphics-libfuzzer$(EXEEXT)"; \
+	corpus="$(FUZZ_COMPONENT_CORPUS)/coregraphics"; \
+	mkdir -p "$$corpus"; \
+	echo "fuzz[loader:coregraphics]: running $$target $(FUZZ_COMPONENT_ARGS) $$corpus"; \
+	exec "$$target" $(FUZZ_COMPONENT_ARGS) "$$corpus"
+else
+run-loader-coregraphics:
+	@echo "error: coregraphics loader fuzz harness is unavailable in this build" >&2; \
+	exit 1
+endif
+
+if HAVE_WIC
+run-loader-wic: fuzz-loader-wic-libfuzzer$(EXEEXT)
+	@set -eu; \
+	target="$(abs_builddir)/fuzz-loader-wic-libfuzzer$(EXEEXT)"; \
+	corpus="$(FUZZ_COMPONENT_CORPUS)/wic"; \
+	mkdir -p "$$corpus"; \
+	echo "fuzz[loader:wic]: running $$target $(FUZZ_COMPONENT_ARGS) $$corpus"; \
+	exec "$$target" $(FUZZ_COMPONENT_ARGS) "$$corpus"
+else
+run-loader-wic:
+	@echo "error: wic loader fuzz harness is unavailable in this build" >&2; \
+	exit 1
+endif
 
 run-struct-%: fuzz-loader-builtin-struct-%-libfuzzer$(EXEEXT)
 	@set -eu; \
