tests: don't export test_name to tests

diff --git a/build-aux/lso-tap-driver.sh.in b/build-aux/lso-tap-driver.sh.in
--- a/build-aux/lso-tap-driver.sh.in
+++ b/build-aux/lso-tap-driver.sh.in
@@ -55,7 +55,7 @@ EOF
 while [ $# -gt 0 ]; do
   case "$1" in
     --help) usage ;;
-    --test-name) arg_test_name=${2-}; shift ;;
+    --test-name) test_name=${2-}; shift ;;
     --log-file)  log_file=${2-}; shift ;;
     --trs-file)  trs_file=${2-}; shift ;;
     --ignore-exit) ignore_exit=yes ;;
@@ -80,7 +80,7 @@ while [ $# -gt 0 ]; do
   shift
 done
 
-[ -n "${arg_test_name}" ] || { echo "lso-tap-driver.sh: missing --test-name" >&2; usage; }
+[ -n "${test_name}" ] || { echo "lso-tap-driver.sh: missing --test-name" >&2; usage; }
 [ -n "${log_file}" ]  || { echo "lso-tap-driver.sh: missing --log-file" >&2; usage; }
 [ -n "${trs_file}" ]  || { echo "lso-tap-driver.sh: missing --trs-file" >&2; usage; }
 [ $# -ge 1 ] || { echo "lso-tap-driver.sh: missing TEST-SCRIPT" >&2; usage; }
@@ -97,8 +97,7 @@ timeout_budget=${test_timeout:-90}
 kill_delay=10
 
 test_script=$1
-test_name_base=${arg_test_name##*[/\\]}
-test_name=${test_name_base%.t}
+test_name_base=${test_name##*[/\\]}
 test_dir=${test_script%[/\\]*}
 if [ "${test_dir}" = "${test_script}" ]; then
   test_dir=.
@@ -106,7 +105,6 @@ fi
 category_name=${test_dir#*tests/}
 artifact_root="${TOP_BUILDDIR}/tests/_artifacts"
 ARTIFACT_LOCAL_DIR="${artifact_root}/${category_name}/${test_name_base}"
-export test_name
 export test_dir
 export category_name
 export ARTIFACT_LOCAL_DIR
@@ -206,7 +204,7 @@ fi
 # Also write :global-test-result:, :recheck:, :copy-in-global-log: for convenience
 # (Automake recognizes these fields). :contentReference[oaicite:5]{index=5}
 "$AM_TAP_AWK" < "$log_file" \
-  -v test_name="$arg_test_name" \
+  -v test_name="$test_name" \
   -v rc="$rc" \
   -v ignore_exit="$ignore_exit" \
   -v comments="$comments" \
